### ISSUE TITLE
Any plans to add iOS support?

### ISSUE THREAD

**Issue by jaysson** [fayeed/flutter_freshchat#1]
If you are not already working on it, I can help.

**Comment by fayeed** [comment]
@jaysson Yeah sure, I don't have a mac so I wasn't able to add IOS support.

**Comment by jaysson** [comment]
Submitted a pull request:

https://github.com/fayeed/flutter_freshchat/pull/3

**Comment by fayeed** [comment]
I have merged the #3 commit and also closing this issue.
