### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by daadu** [fayeed/flutter_freshchat#14]
**Is your feature request related to a problem? Please describe.**
Migrating to AndroidX is inevitable!!

**Describe the solution you'd like**
Update the freshdesk android dependency to the latest version. I had requested this to the freshdesk team they now support AndroidX. Check [this issue](https://github.com/freshdesk/freshchat-android/issues/49)

**Describe alternatives you've considered**
Nil

**Additional context**
Mark the latest version number that doesn't support AndroidX and put that in README.md

**Comment by fayeed** [comment]
I will update the Freshchat SDK to version `2.9.0`. But if you are facing problems in the meantime have you tried adding these properties to `gradle.properties`

```
android.enableJetifier=true
android.useAndroidX=true
```

**Comment by fayeed** [comment]
@daadu Updated the package to version `1.2.1` this includes the new Freshchat android version `2.9.0`.

**Comment by amitkhairnar44** [comment]
@fayeed Please migrate it to **AndroidX**
App is crashing at start and the app is already migrated to AndroidX.

```
java.lang.RuntimeException: Unable to get provider android.support.v4.content.FileProvider: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.FileProvider" on path: DexPathList[[zip file "/data/app/com.clickparamount.agency-WxREl3jYvqli1_ag0EefAw==/base.apk"],nativeLibraryDirectories=[/data/app/com.clickparamount.agency-WxREl3jYvqli1_ag0EefAw==/lib/arm64, /data/app/com.clickparamount.agency-WxREl3jYvqli1_ag0EefAw==/base.apk!/lib/arm64-v8a, /system/lib64]]
```

**Comment by fayeed** [comment]
@amitkhairnar44 you just need to change this line in `AndroidManifest.xml`.

From this:
```xml
        <provider
        android:name="android.support.v4.content.FileProvider">
```

To this:
```xml
        <provider
        android:name="androidx.core.content.FileProvider">
```

**Comment by amitkhairnar44** [comment]
@fayeed Thank you
Issue is resolved now

Please update the documentation
