### ISSUE TITLE
DISCUSSION on duplicated info.plist error

### ISSUE THREAD

**Issue by savy-91** [fayeed/flutter_freshchat#17]
Hi! Do you have any idea how the error related to the duplicated info.plist could be fixed once and for good?

We are moving towards CI/CD and having this error always breaks the build, I'd be glad to help but I have no idea where to start looking :)

**Comment by fayeed** [comment]
@savy-91 As mentioned in the README this has something to do with Freshchat IOS SDK, It might be resolved by removing the `Info.plist` file in the framework, I haven't tried it yet so I don't know if it would break the SDK or not. I was going to update the Freshchat IOS SDK so I will take a look at it at that time.

**Comment by fayeed** [comment]
Hi, @savy-91 I have fixed this issue by removing the two extra `info.plist` present in the Freshchat-IOS SDK. You can check this `1.2.2` version of the package for this fix. 

If you encounter this problem or some other due to the changes do let me know.

**Comment by savy-91** [comment]
I confirm this solved the issue, thanks a lot again!
