### ISSUE TITLE
Option to disable upload picture from gallery

### ISSUE THREAD

**Issue by rahuldange09** [fayeed/flutter_freshchat#19]
Is it possible to add parameter to disable 'Upload from gallery' option same like camera.
It would be great if option is there to disable that.

**Comment by fayeed** [comment]
@rahuldange09 I have updated the package to `1.2.4` with all the supported properties of `FreshchatConfig`.

**Comment by rahuldange09** [comment]
Well Thanks for quick change. 👍

**Comment by Sagar268380** [comment]
my  faqs button is not working i don't know why
