### ISSUE TITLE
Customization through dart code

### ISSUE THREAD

**Issue by krel024** [fayeed/flutter_freshchat#32]
Currently I can not find how to customize the theme.

It will be nice to have a way to customize the freshchat as they explain in their documentation.

Example:
```dart
FlutterFreshchat.init(
  appID: '<appID>',
  appKey: '<appKey>',
  navigatorBar: NavigatorBarStyle(
    backgroudColor: Colors.red,
  ),
);
```

**Comment by ccfiel** [comment]
yes this would be a great feature.

**Comment by fayeed** [comment]
@krel024 @ccfiel This is not possible with Flutter right now as you need to add Custom themes at native level you can refer the docs for [IOS](https://support.freshchat.com/support/solutions/articles/229814-freshchat-ios-sdk-themes) & [Android](https://support.freshchat.com/support/solutions/articles/229492-freshchat-android-sdk-themes-and-customizations) here.

**Comment by ccfiel** [comment]
@fayeed thanks for the update! ☺️

**Comment by DmytroB36** [comment]
@fayeed Could you please indicate on what path inside the plugin I can find the native code for android and for ios to modify the theme?

**Comment by fayeed** [comment]
> @krel024 @ccfiel This is not possible with Flutter right now as you need to add Custom themes at native level you can refer the docs for [IOS](https://support.freshchat.com/support/solutions/articles/229814-freshchat-ios-sdk-themes) & [Android](https://support.freshchat.com/support/solutions/articles/229492-freshchat-android-sdk-themes-and-customizations) here.

@nilecrocodile Follow the link mentioned in this reply
