### ISSUE TITLE
Could not build Objective-C module 'flutter_freshchat'

### ISSUE THREAD

**Issue by krel024** [fayeed/flutter_freshchat#33]
This is happening since version 1.3.0.
```dart
info flutter.tools <unknown>:0: error: could not build Objective-C module 'flutter_freshchat'
```
**Desktop (please complete the following information):**
 - OS: Mac
 - Device: IOS Simulator
 - Version: 13.4

**Comment by nimi0112** [comment]
I am also facing the same in version 1.3.0. I can't even run the sample app.

**Comment by lessthanno** [comment]
I made a version comparison https://github.com/fayeed/flutter_freshchat/issues/34

**Comment by fayeed** [comment]
@krel024 take a look at issue #31 it should resolve this issue and I am closing this.
