### ISSUE TITLE
[BUG] The whole new version（v1.3.0） is wrong

### ISSUE THREAD

**Issue by lessthanno** [fayeed/flutter_freshchat#34]
**Desktop (please complete the following information):**
 - OS: [e.g. Mac]
 - Device: [e.g. iPhoneX] | Emulator
 - Version [e.g. 1.3.0]

**Additional context**'

Comparison of versions

v 1.3.0 
![image](https://user-images.githubusercontent.com/6271483/79426907-6e740100-7ff6-11ea-92bd-6d8e7453e9e7.png)

v 1.2.6 
![image](https://user-images.githubusercontent.com/6271483/79427077-aa0ecb00-7ff6-11ea-8673-007f2d13103d.png)

v 1.2.6 icon file missing

v1.3.0 a lot less files!!!!

But v1.2.6 can run! 
please fix !!!!!!!! THX

**Comment by ccfiel** [comment]
I have same problem

**Comment by lessthanno** [comment]
> I have same problem

now.I try to change pod/development pods/flutter_freshchat file and update freshchat sdk to 3.4.0

![image](https://user-images.githubusercontent.com/6271483/79534801-2adcce00-80ae-11ea-95c9-011c5a27e145.png)

Temporarily so useful！！！

**Comment by ccfiel** [comment]
@lessthanno its already 3.4 in version 1.3.0. What version are you?

https://github.com/fayeed/flutter_freshchat/blob/master/ios/flutter_freshchat.podspec#L14

**Comment by lessthanno** [comment]
> @lessthanno its already 3.4 in version 1.3.0. What version are you?
> 
> https://github.com/fayeed/flutter_freshchat/blob/master/ios/flutter_freshchat.podspec#L14

I use version 1.2.6

**Comment by mohdkhmais** [comment]
@lessthanno any solution yet ?

**Comment by daadu** [comment]
@mohdkhmais I have filed PR #36 

I would encourage you to test it on your build by adding this to your pubspec.yaml

```yaml
flutter_freshchat: #^1.3.0
    git:
      url: "https://github.com/daadu/flutter_freshchat.git"
```

**Comment by lessthanno** [comment]
> @mohdkhmais I have filed PR #36
> 
> I would encourage you to test it on your build by adding this to your pubspec.yaml
> 
> ```yaml
> flutter_freshchat: #^1.3.0
>     git:
>       url: "https://github.com/daadu/flutter_freshchat.git"
> ```

Cool ！！this bug is  fixed ！！！THX

**Comment by mohdkhmais** [comment]
Hi @lessthanno i have just tried your version but no luck

`2020-04-26 09:21:19.056883+0300 Runner[9716:55006] +[UIImage fd_imageWithData:]: unrecognized selector sent to class 0x7fff897b0d10
2020-04-26 09:21:19.078244+0300 Runner[9716:55006] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[UIImage fd_imageWithData:]: unrecognized selector sent to class 0x7fff897b0d10'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23e3dcce __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50b3b9b2 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23e5e8f4 +[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23e426cc ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23e449b8 _CF_forwarding_prep_0 + 120
	5   flutter_freshchat                   0x0000000108ad7383 -[FDWebImageDownloaderOperation URLSession:task:didCompleteWithError:] + 476
	6   flutter_freshchat                   0x0000000108b40ebe -[FDWebImageDownloader URLSession:task:didCompleteWithError:] + 113
	7   CFNetwork                           0x00007fff230f3297 _CFNetworkHTTPConnectionCacheSetLimit + 207379
	8   Foundation                          0x00007fff25914e4c __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7
	9   Foundation                          0x00007fff25914d6d -[NSBlockOperation main] + 80
	10  Foundation                          0x00007fff25917c9c __NSOPERATION_IS_INVOKING_MAIN__ + 17
	11  Foundation                          0x00007fff25913fae -[NSOperation start] + 731
	12  Foundation                          0x00007fff259185e0 __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ + 17
	13  Foundation                          0x00007fff25918100 __NSOQSchedule_f + 182
	14  libdispatch.dylib                   0x000000010a5054dc _dispatch_block_async_invoke2 + 83
	15  libdispatch.dylib                   0x000000010a4f6e8e _dispatch_client_callout + 8
	16  libdispatch.dylib                   0x000000010a4f97a3 _dispatch_continuation_pop + 552
	17  libdispatch.dylib                   0x000000010a4f8bbb _dispatch_async_redirect_invoke + 771
	18  libdispatch.dylib                   0x000000010a508399 _dispatch_root_queue_drain + 351
	19  libdispatch.dylib                   0x000000010a508ca6 _dispatch_worker_thread2 + 135
	20  libsystem_pthread.dylib             0x00007fff51b9e9f7 _pthread_wqthread + 220
	21  libsystem_pthread.dylib             0x00007fff51b9db77 start_wqthread + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) `

**Comment by rahuldange09** [comment]
> Hi @daadu i have just tried your version but no luck
> 
> 2020-04-26 09:21:19.056883+0300 Runner[9716:55006] +[UIImage fd_imageWithData:]: unrecognized selector sent to class 0x7fff897b0d10
> 2020-04-26 09:21:19.078244+0300 Runner[9716:55006] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '+[UIImage fd_imageWithData:]: unrecognized selector sent to class 0x7fff897b0d10'
> *** First throw call stack:
> (
> 0 CoreFoundation 0x00007fff23e3dcce __exceptionPreprocess + 350
> 1 libobjc.A.dylib 0x00007fff50b3b9b2 objc_exception_throw + 48
> 2 CoreFoundation 0x00007fff23e5e8f4 +[NSObject(NSObject) doesNotRecognizeSelector:] + 132
> 3 CoreFoundation 0x00007fff23e426cc _**forwarding**_ + 1436
> 4 CoreFoundation 0x00007fff23e449b8 _CF_forwarding_prep_0 + 120
> 5 flutter_freshchat 0x0000000108ad7383 -[FDWebImageDownloaderOperation URLSession:task:didCompleteWithError:] + 476
> 6 flutter_freshchat 0x0000000108b40ebe -[FDWebImageDownloader URLSession:task:didCompleteWithError:] + 113
> 7 CFNetwork 0x00007fff230f3297 _CFNetworkHTTPConnectionCacheSetLimit + 207379
> 8 Foundation 0x00007fff25914e4c **NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK** + 7
> 9 Foundation 0x00007fff25914d6d -[NSBlockOperation main] + 80
> 10 Foundation 0x00007fff25917c9c **NSOPERATION_IS_INVOKING_MAIN** + 17
> 11 Foundation 0x00007fff25913fae -[NSOperation start] + 731
> 12 Foundation 0x00007fff259185e0 **NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION** + 17
> 13 Foundation 0x00007fff25918100 __NSOQSchedule_f + 182
> 14 libdispatch.dylib 0x000000010a5054dc _dispatch_block_async_invoke2 + 83
> 15 libdispatch.dylib 0x000000010a4f6e8e _dispatch_client_callout + 8
> 16 libdispatch.dylib 0x000000010a4f97a3 _dispatch_continuation_pop + 552
> 17 libdispatch.dylib 0x000000010a4f8bbb _dispatch_async_redirect_invoke + 771
> 18 libdispatch.dylib 0x000000010a508399 _dispatch_root_queue_drain + 351
> 19 libdispatch.dylib 0x000000010a508ca6 _dispatch_worker_thread2 + 135
> 20 libsystem_pthread.dylib 0x00007fff51b9e9f7 _pthread_wqthread + 220
> 21 libsystem_pthread.dylib 0x00007fff51b9db77 start_wqthread + 15
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException
> (lldb)

Hi, @mohdkhmais 
Please try this and check if it works
https://github.com/fayeed/flutter_freshchat/issues/31#issuecomment-619436356

**Comment by daadu** [comment]
@mohdkhmais Looks like it is crashing of some other reason. I am not an iOS developer

**Comment by smkhalsa** [comment]
@fayeed has this been fixed?

**Comment by fayeed** [comment]
@smkhalsa Yeah check the pinned issue #31
