### ISSUE TITLE
App crashes when FlutterFreshchat.showConversations() or FlutterFreshchat.showFAQs() is called on androidx

### ISSUE THREAD

**Issue by colkencon** [fayeed/flutter_freshchat#39]
when FlutterFreshchat.showConversations() or FlutterFreshchat.showFAQs(), it throws an exception and crashes the app. Kindly assist

Version Used
flutter_freshchat: ^1.3.0

 
            android:name="androidx.core.content.FileProvider"
            android:authorities="com.freshchat.flutter_freshchat.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/freshchat_file_provider_paths" />

Exception 
D/AndroidRuntime(29959): Shutting down VM
E/AndroidRuntime(29959): FATAL EXCEPTION: main
E/AndroidRuntime(29959): Process: com.fresh_chat.test, PID: 29959
E/AndroidRuntime(29959): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fresh_chat.test/com.freshchat.consumer.sdk.activity.ChannelListActivity}: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class androidx.appcompat.widget.ActionBarOverlayLayout
E/AndroidRuntime(29959): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3114)
E/AndroidRuntime(29959): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
E/AndroidRuntime(29959): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E/AndroidRuntime(29959): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(29959): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(29959): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
E/AndroidRuntime(29959): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(29959): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(29959): 	at android.app.ActivityThread.main(ActivityThread.java:7050)
E/AndroidRuntime(29959): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29959): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/AndroidRuntime(29959): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
E/AndroidRuntime(29959): Caused by: android.view.InflateException: Binary XML file line #17: Binary XML file line #17: Error inflating class androidx.appcompat.widget.ActionBarOverlayLayout
E/AndroidRuntime(29959): Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class androidx.appcompat.widget.ActionBarOverlayLayout
E/AndroidRuntime(29959): Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.appcompat.widget.ActionBarOverlayLayout" on path: DexPathList[[zip file "/data/app/com.fresh_chat.test,-koNRblhvzOXMNhm3ZhRcwA==/base.apk"],nativeLibraryDirectories=[/data/app/com.fresh_chat.test-koNRblhvzOXMNhm3ZhRcwA==/lib/arm64, /data/app/com.fresh_chat.test-koNRblhvzOXMNhm3ZhRcwA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]

E/AndroidRuntime(29959): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
E/AndroidRuntime(29959): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(29959): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(29959): 	at android.view.LayoutInflater.createView(LayoutInflater.java:606)
E/AndroidRuntime(29959): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
E/AndroidRuntime(29959): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
E/AndroidRuntime(29959): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
E/AndroidRuntime(29959): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
E/AndroidRuntime(29959): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
E/AndroidRuntime(29959): 	at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:749)
E/AndroidRuntime(29959): 	at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659)
E/AndroidRuntime(29959): 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:552)
E/AndroidRuntime(29959): 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
E/AndroidRuntime(29959): 	at com.freshchat.consumer.sdk.activity.ChannelListActivity.onCreate(Unknown Source:15)
E/AndroidRuntime(29959): 	at android.app.Activity.performCreate(Activity.java:7327)
E/AndroidRuntime(29959): 	at android.app.Activity.performCreate(Activity.java:7318)
E/AndroidRuntime(29959): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
E/AndroidRuntime(29959): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)
E/AndroidRuntime(29959): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
E/AndroidRuntime(29959): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
E/AndroidRuntime(29959): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(29959): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(29959): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
E/AndroidRuntime(29959): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(29959): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(29959): 	at android.app.ActivityThread.main(ActivityThread.java:7050)
E/AndroidRuntime(29959): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29959): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
E/AndroidRuntime(29959): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
E/AndroidRuntime(29959): 	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/core/view/NestedScrollingParent3;
E/AndroidRuntime(29959): 		at java.lang.VMClassLoader.findLoadedClass(Native Method)
E/AndroidRuntime(29959): 		at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
E/AndroidRuntime(29959): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
E/AndroidRuntime(29959): 		... 27 more
E/AndroidRuntime(29959): 	Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.core.view.NestedScrollingParent3" on path: DexPathList[[zip file "/data/app/com.fresh_chat.test-koNRblhvzOXMNhm3ZhRcwA==/base.apk"],nativeLibraryDirectories=[/data/app/com.fresh_chat.test-koNRblhvzOXMNhm3ZhRcwA==/lib/arm64, /data/app/com.fresh_chat.test-koNRblhvzOXMNhm3ZhRcwA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
E/AndroidRuntime(29959): 		at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
E/AndroidRuntime(29959): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(29959): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(29959): 		... 30 more

**Comment by fayeed** [comment]
@colkencon I think this has something to do with `androidx`, I just released a new version can you try that `1.3.1`

**Comment by olaide-ekolere** [comment]
I resolved this issue by first adding xmlns:tools="http://schemas.android.com/tools" to the manifest tag in the AndroidManifest.xml then add tools:replace="android:authorities" to the provider tag then tools:replace="android:resource" to the meta-data tag in the provider tag should resolve the problem.
