### ISSUE TITLE
ContentProvider name clashing when 2 app with this same plugin installed

### ISSUE THREAD

**Issue by daadu** [fayeed/flutter_freshchat#4]
When 2 apps with this plugin are installed on the same phone. The second app fails to install because of the provider name clashing.

**Comment by fayeed** [comment]
Thanks for reporting this. I will get back after I have tested this.

**Comment by fayeed** [comment]
@daadu , I have fixed this, add this to your AndroidManifest.xml inside your `<application/>` tag:

replace the `android:authorities:"<your package URI here>.provider"`

```
<provider
        android:name="android.support.v4.content.FileProvider"
        android:authorities="com.freshchat.flutter_freshchat_example.provider"
        android:exported="false"
        android:grantUriPermissions="true">
        <meta-data
            android:name="android.support.FILE_PROVIDER_PATHS"
            android:resource="@xml/freshchat_file_provider_paths" />
    </provider>
```
also inside you `Strings.xml` file add this:

```
<?xml version="1.0" encoding="utf-8" ?>
<resources>
    <string name="freshchat_file_provider_authority">(your package URI here).provider</string>
</resources>
```

**Comment by daadu** [comment]
I tested with new provider it works. Thanks for quick response.
