### ISSUE TITLE
Infinite Loading - Missing Domain Config - freshchatInit

### ISSUE THREAD

**Issue by naiduasn** [fayeed/flutter_freshchat#40]
**Describe the bug**
I was trying to use freshchat domain in the config to address below issue
https://github.com/freshdesk/freshchat-android/issues/61

but i do not see an option in this lib.

**To Reproduce**

**Expected behavior**
config should be available to add domain

**Additional context**

**Comment by fayeed** [comment]
@naiduasn Merged your PR and have released a new version `1.3.1`
