### ISSUE TITLE
[BUG] Unsupported version of Picaso found

### ISSUE THREAD

**Issue by VytorCalixto** [fayeed/flutter_freshchat#42]
**Describe the bug**
The packages throws an "Unsupported version of Picaso found." error and doesn't initialize.

**To Reproduce**
Add the FlutterFreshchat and call the init method. The error below should appear.

Error log:
```
E/MethodChannel#flutter_freshchat( 3862): Failed to handle method call
E/MethodChannel#flutter_freshchat( 3862): java.lang.IllegalArgumentException: Unsupported version of Picasso found. Please create and set custom Image loader using Freshchat.setImageLoader().
E/MethodChannel#flutter_freshchat( 3862): 	at com.freshchat.consumer.sdk.j.ba.fX(Unknown Source:29)
E/MethodChannel#flutter_freshchat( 3862): 	at com.freshchat.consumer.sdk.Freshchat.init(Unknown Source:55)
E/MethodChannel#flutter_freshchat( 3862): 	at com.freshchat.flutter_freshchat.FlutterFreshchatPlugin.onMethodCall(FlutterFreshchatPlugin.java:65)
E/MethodChannel#flutter_freshchat( 3862): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
E/MethodChannel#flutter_freshchat( 3862): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter_freshchat( 3862): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
E/MethodChannel#flutter_freshchat( 3862): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter_freshchat( 3862): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#flutter_freshchat( 3862): 	at android.os.Looper.loop(Looper.java:197)
E/MethodChannel#flutter_freshchat( 3862): 	at android.app.ActivityThread.main(ActivityThread.java:7860)
E/MethodChannel#flutter_freshchat( 3862): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter_freshchat( 3862): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#flutter_freshchat( 3862): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Device: Samsung A10
 - Package Version 1.3.0
- Flutter version 1.17.1

**Comment by fayeed** [comment]
@VytorCalixto Thanks for reporting this issue it was a problem with Freshchat Andriod SDK here's the issue: https://github.com/freshdesk/freshchat-android/issues/46#issuecomment-493979741

It's an easy fix I will update the package and let you know.

**Comment by lakshyapunhani** [comment]
Unhandled Exception: PlatformException(error, Unsupported version of Picasso found. Please create and set custom Image loader using Freshchat.setImageLoader()., null)

**Comment by fayeed** [comment]
@VytorCalixto @lakshyapunhani I was not able to reproduce this error on my end but since there was an issue in the official Freshchat android plugin, I have implemented the fix they mentioned. That should fix the problem.

**Comment by olaide-ekolere** [comment]
> @VytorCalixto @lakshyapunhani I was not able to reproduce this error on my end but since there was an issue in the official Freshchat android plugin, I have implemented the fix they mentioned. That should fix the problem.

To reproduce, use firebase-in-app-messaging in pubspec
