### ISSUE TITLE
open conversations screen

### ISSUE THREAD

**Issue by alhasan-s-aboobaid** [fayeed/flutter_freshchat#45]
when i open conversations screen it does not open a list of conversations, it take me directly to messages screen. how to show a list of conversations?

**Comment by fayeed** [comment]
You need to do this on the Freshchat side refer to their docs.

> In response to specific UI events like a menu selection or button on click event, invoke the showConversations() API to launch the Conversation Flow. If the app has multiple channels configured, the user will see the channel list. Channel list is ordered as specified in the Dashboard (link to channel list in dashboard) when there are no messages. When messages are present, the order is based on most recently interacted channel. 

Note | Only Message Channels with visibility set to "Visible to all users" will be displayed when using showConversations() API
-- | --
