### ISSUE TITLE
[BUG]  Not build Objective-C module 'flutter_freshchat'

### ISSUE THREAD

**Issue by dot-wei** [fayeed/flutter_freshchat#46]
**Describe the bug**
```sh
#import "Headers/flutter_freshchat-umbrella.h"
        ^
/Users/bob/mobilestone/LinkFresh-app/ios/Pods/Target Support Files/flutter_freshchat/flutter_freshchat-umbrella.h:13:9: note: in file included from /Users/bob/mobilestone/LinkFresh-app/ios/Pods/Target Support Files/flutter_freshchat/flutter_freshchat-umbrella.h:13:
#import "FlutterFreshchatPlugin.h"
        ^
/Users/bob/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.3.2/ios/Classes/FlutterFreshchatPlugin.h:2:9: error: include of non-modular header inside framework module 'flutter_freshchat.FlutterFreshchatPlugin': '/Users/bob/mobilestone/LinkFresh-app/ios/Pods/FreshchatSDK/FreshchatSDK/FreshchatSDK.h'
#import "FreshchatSDK.h"
        ^
<unknown>:0: error: could not build Objective-C module 'flutter_freshchat'
```
**To Reproduce**
I don't know much about IOS, so follow the flow of IOS in README.

**Desktop**
 - OS: [Mac]
 - Device: iPhoneX
 - Version Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101)

**Comment by GuruJohn** [comment]
Seeing the same problem when trying to build the example.

**Comment by fayeed** [comment]
@GuruJohn @dot-wei Take a look at issue #31 that should fix the issue.

**Comment by dot-wei** [comment]
> @GuruJohn @dot-wei Take a look at issue #31 that should fix the issue.
I tried to use the solution in this isuue, but failed. Later, I decide used it with the object-c version of the repository fork. Thank you for your reply.
