### ISSUE TITLE
Feature Request : setting phone and phoneCountry and other arbitrary user attributes

### ISSUE THREAD

**Issue by daadu** [fayeed/flutter_freshchat#5]
FreshChat has this API to set User attributes (to know more about the user in the dashboard while chatting), phone number especially is important because it is linked with other FreshWork CRM services.

**Comment by fayeed** [comment]
Ok I see that I think we should have User class to handle that.

**Comment by fayeed** [comment]
@daadu also fixed this. Added a `User `Object which you could pass to the `updateUserInfo()` method. Do check the [README.md](https://github.com/fayeed/flutter_freshchat/blob/master/README.md) for more details.

**Comment by daadu** [comment]
This works. Is there a way to also have custom user attributes as mentioned  in [this documentation - 3.2 Section](https://support.freshchat.com/support/solutions/articles/229319-freshchat-android-sdk-integration-steps)

**Comment by fayeed** [comment]
It should but I haven't added that. I will update the code later.

**Comment by daadu** [comment]
Cool. I guess should keep this issue open, I don't know iOS development - or else would have filled PR myself. Thanks again for this plugin.

**Comment by fayeed** [comment]
Yeah sure, no problem.

**Comment by daadu** [comment]
current changes - custom_provider_name and User properties will also work with iOS right? Seems like you haven't modified ios directory at all.

**Comment by fayeed** [comment]
setting the user won't work for IOS, as I don't have a mac to test the changes.

**Comment by fayeed** [comment]
maybe, @jaysson can help with this. He implemented the IOS part for this plugin

**Comment by fayeed** [comment]
@daadu updated the code & can you check it on IOS and let me know if it works
