### ISSUE TITLE
[BUG] package:flutter_freshchat Cannot run with sound null safety

### ISSUE THREAD

**Issue by therngbtg** [fayeed/flutter_freshchat#59]
I can't run with Null-safety
[
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:

 - package:flutter_freshchat

For solutions, see https://dart.dev/go/unsound-null-safety

FAILURE: Build failed with an exception.
]

**Comment by fayeed** [comment]
There is a official package now https://pub.dev/packages/freshchat_sdk
