### ISSUE TITLE
flutter_freshchat` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

### ISSUE THREAD

**Issue by MilenaSousa** [fayeed/flutter_freshchat#9]
- `flutter_freshchat` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0/lib/cocoapods/installer/xcode/target_validator.rb:122:in `verify_swift_pods_swift_version'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0/lib/cocoapods/installer/xcode/target_validator.rb:37:in `validate!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0/lib/cocoapods/installer.rb:578:in `validate_targets'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0/lib/cocoapods/installer.rb:158:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0/lib/cocoapods/command/install.rb:51:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.7.0/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'
Error output from CocoaPods:
↳
        WARNING: CocoaPods requires your terminal to be using UTF-8 encoding.
        Consider adding the following to ~/.profile:
        export LANG=en_US.UTF-8

I already tried to add "config.build_settings['SWIFT_VERSION'] = '4.2'", but it didn't work

**Comment by fayeed** [comment]
@MilenaSousa does your ios uses swift or objective-c?

**Comment by MilenaSousa** [comment]
I think it is swift

here is the plugin code
https://github.com/fayeed/flutter_freshchat/tree/master/ios

Em ter, 23 de jul de 2019 às 14:31, Fayeed Pawaskar <
notifications@github.com> escreveu:

**Comment by MilenaSousa** [comment]
how do i know if my ios uses swift or object-c?

Em ter, 23 de jul de 2019 às 14:31, Fayeed Pawaskar <
notifications@github.com> escreveu:

**Comment by fayeed** [comment]
I researched the problem and it is something that happens with all Flutter plugins, take a look at this [flutter/flutter#25676](https://github.com/flutter/flutter/issues/25676).

The above steps should resolve this issue.

**Comment by MilenaSousa** [comment]
> @MilenaSousa does your ios uses swift or objective-c? also, try this below steps:
> 
> 1. Bridging Header must be created.
>    Open the project with XCode. Then choose `File -> New -> File -> Swift File`.
>    A dialog will be displayed when creating the swift file(Since this file is deleted, any name can be used.).
>    XCode will ask you if you wish to create Bridging Header, click yes.
> 2. Make sure you have `use_frameworks!` in the Runner block, in `ios/Podfile`。
> 3. Make sure you have `SWIFT_VERSION` 4.2 selected in you `XCode -> Build Settings`
> 4. Do `flutter clean`.
> 5. Go to your ios folder, delete Podfile.lock and Pods folder and then execute `pod install --repo-update`

**After I did that I had this error:**

    In file included from /Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/barcode_scan-1.0.0/ios/Classes/BarcodeScannerViewController.m:5:
    /Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/barcode_scan-1.0.0/ios/Classes/BarcodeScannerViewController.h:19:3: note: method 'initWithOptions:' declared here
      -(id) initWithOptions:(NSDictionary *) options;
      ^
    1 warning generated.
    In file included from /Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/barcode_scan-1.0.0/ios/Classes/BarcodeScanPlugin.m:1:
    /Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/barcode_scan-1.0.0/ios/Classes/BarcodeScanPlugin.h:12:1: warning: retain'ed block property does not copy the block - use copy attribute instead [-Wobjc-noncopy-retain-block-property]
    @property(nonatomic, retain) FlutterResult result;
    ^
    1 warning generated.
    /Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/barcode_scan-1.0.0/ios/Classes/ScannerOverlay.m:25:12: warning: unused variable 'scanLineColor' [-Wunused-variable]
      UIColor *scanLineColor = UIColor.redColor;
               ^
    1 warning generated.

**Comment by MilenaSousa** [comment]
> @MilenaSousa does your ios uses swift or objective-c? also, try this below steps:
> 
> 1. Bridging Header must be created.
>    Open the project with XCode. Then choose `File -> New -> File -> Swift File`.
>    A dialog will be displayed when creating the swift file(Since this file is deleted, any name can be used.).
>    XCode will ask you if you wish to create Bridging Header, click yes.
> 2. Make sure you have `use_frameworks!` in the Runner block, in `ios/Podfile`。
> 3. Make sure you have `SWIFT_VERSION` 4.2 selected in you `XCode -> Build Settings`
> 4. Do `flutter clean`.
> 5. Go to your ios folder, delete Podfile.lock and Pods folder and then execute `pod install --repo-update`

**After I did that I had this error:** 

Xcode's output:
↳
    warning: no rule to process file '/Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.1.4/ios/Classes/FreshchatSDK/FreshchatModels.bundle/FreshchatModel.momd/FreshchatModel 2.omo' of type file for architecture x86_64
    warning: no rule to process file '/Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.1.4/ios/Classes/FreshchatSDK/libFDFreshchatSDK.a' of type archive.ar for architecture x86_64
    warning: no rule to process file '/Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.1.4/ios/Classes/FreshchatSDK/LICENSE' of type text for architecture x86_64
    warning: no rule to process file '/Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.1.4/ios/Classes/FreshchatSDK/FCResources.bundle/Themes/normalize.css' of type text.css for architecture x86_64
    warning: no rule to process file '/Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.1.4/ios/Classes/FreshchatSDK/ReleaseNotes.txt' of type text for architecture x86_64
    === BUILD TARGET barcode_scan OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.1.4/ios/Classes/SwiftFlutterFreshchatPlugin.swift:65:47: error: type 'String?' does not conform to protocol 'Sequence'
                    for (kind, value) in arguments["custom_property_list"] {
                                                  ^
    /Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/barcode_scan-1.0.0/ios/Classes/BarcodeScannerViewController.m:10:17: warning: method definition for 'initWithOptions:' not found [-Wincomplete-implementation]
    @implementation BarcodeScannerViewController {
                    ^
    In file included from /Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/barcode_scan-1.0.0/ios/Classes/BarcodeScannerViewController.m:5:
    /Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/barcode_scan-1.0.0/ios/Classes/BarcodeScannerViewController.h:19:3: note: method 'initWithOptions:' declared here
      -(id) initWithOptions:(NSDictionary *) options;
      ^
    1 warning generated.
    In file included from /Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/barcode_scan-1.0.0/ios/Classes/BarcodeScanPlugin.m:1:
    /Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/barcode_scan-1.0.0/ios/Classes/BarcodeScanPlugin.h:12:1: warning: retain'ed block property does not copy the block - use copy attribute instead [-Wobjc-noncopy-retain-block-property]
    @property(nonatomic, retain) FlutterResult result;
    ^
    1 warning generated.
    /Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/barcode_scan-1.0.0/ios/Classes/ScannerOverlay.m:25:12: warning: unused variable 'scanLineColor' [-Wunused-variable]
      UIColor *scanLineColor = UIColor.redColor;
Launching lib/main.dart on iPhone XR in debug mode...
Xcode build done.                                            9,1s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
               ^
    1 warning generated.

**Comment by fayeed** [comment]
@MilenaSousa I think I know where the problem might be, but wanted to ask you what are you updating user info? if so are you providing `customProperties` to Freshchat. The reason is that I looked through the code and I forgot to check if a `customProperies` is passed or not so if it is not passed it will crash plugin.

**Comment by MilenaSousa** [comment]
I wasn't adding the customProperies yet

After i added half the errors disappeared, but there are still some

**I added this to initState:** 
    FreshchatUser user = FreshchatUser.initail();
    user.email = "jhon@test.com";
    user.firstName = "jhon";
    user.lastName = "doe";
    user.phoneCountryCode = "+91";
    user.phone = "0123456789";

    Map<String, String> customProperties = Map<String, String>();
    customProperties["loggedIn"] = "true";

    await FlutterFreshchat.updateUserInfo(user: user, customProperties: customProperties);

**The mistakes now are these**
   ** BUILD FAILED **
Xcode's output:
↳
    === BUILD TARGET shared_preferences OF PROJECT Pods WITH CONFIGURATION Debug ===
    warning: no rule to process file '/Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.1.4/ios/Classes/FreshchatSDK/FreshchatModels.bundle/FreshchatModel.momd/FreshchatModel 2.omo' of type file for architecture x86_64
    warning: no rule to process file '/Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.1.4/ios/Classes/FreshchatSDK/libFDFreshchatSDK.a' of type archive.ar for architecture x86_64
    warning: no rule to process file '/Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.1.4/ios/Classes/FreshchatSDK/LICENSE' of type text for architecture x86_64
    warning: no rule to process file '/Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.1.4/ios/Classes/FreshchatSDK/FCResources.bundle/Themes/normalize.css' of type text.css for architecture x86_64
    warning: no rule to process file '/Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.1.4/ios/Classes/FreshchatSDK/ReleaseNotes.txt' of type text for architecture x86_64
    === BUILD TARGET shared_preferences OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.1.4/ios/Classes/SwiftFlutterFreshchatPlugin.swift:65:47: error: type 'String?' does not conform to protocol 'Sequence'
                    for (kind, value) in arguments["custom_property_list"] {
                                                  ^

**Comment by fayeed** [comment]
@MilenaSousa updated the plugin to `1.1.6` try this latest version should fix the problem you have

**Comment by MilenaSousa** [comment]
**I updated it to 1.1.6 and now it's returned**

** BUILD FAILED **
Xcode's output:
↳
    warning: no rule to process file '/Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.1.6/ios/Classes/FreshchatSDK/FreshchatModels.bundle/FreshchatModel.momd/FreshchatModel 2.omo' of type file for architecture x86_64
    warning: no rule to process file '/Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.1.6/ios/Classes/FreshchatSDK/libFDFreshchatSDK.a' of type archive.ar for architecture x86_64
    warning: no rule to process file '/Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.1.6/ios/Classes/FreshchatSDK/LICENSE' of type text for architecture x86_64
    warning: no rule to process file '/Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.1.6/ios/Classes/FreshchatSDK/FCResources.bundle/Themes/normalize.css' of type text.css for architecture x86_64
    warning: no rule to process file '/Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.1.6/ios/Classes/FreshchatSDK/ReleaseNotes.txt' of type text for architecture x86_64
    === BUILD TARGET shared_preferences OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.1.6/ios/Classes/SwiftFlutterFreshchatPlugin.swift:58:44: error: cannot assign value of type 'Any?' to type 'String?'
                    user?.firstName = arguments["first_name"]
                                      ~~~~~~~~~^~~~~~~~~~~~~~
                                                              as! String
    /Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.1.6/ios/Classes/SwiftFlutterFreshchatPlugin.swift:59:43: error: cannot assign value of type 'Any?' to type 'String?'
                    user?.lastName = arguments["last_name"]
                                     ~~~~~~~~~^~~~~~~~~~~~~
                                                            as! String
    /Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.1.6/ios/Classes/SwiftFlutterFreshchatPlugin.swift:60:47: error: cannot assign value of type 'Any?' to type 'String?'
                    user?.phoneNumber  = arguments["phone"]
                                         ~~~~~~~~~^~~~~~~~~
                                                            as! String
    /Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.1.6/ios/Classes/SwiftFlutterFreshchatPlugin.swift:61:40: error: cannot assign value of type 'Any?' to type 'String?'
                    user?.email = arguments["email"]
                                  ~~~~~~~~~^~~~~~~~~
                                                     as! String
    /Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.1.6/ios/Classes/SwiftFlutterFreshchatPlugin.swift:62:51: error: cannot assign value of type 'Any?' to type 'String?'
                    user?.phoneCountryCode = arguments["phone_country_code"]
                                             ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
                                                                             as! String
    /Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.1.6/ios/Classes/SwiftFlutterFreshchatPlugin.swift:66:38: warning: comparing non-optional value of type '[String : Any]' to nil always returns true
                    if (customProperties != nil) {
                        ~~~~~~~~~~~~~~~~ ^  ~~~
    /Users/Milena/documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.1.6/ios/Classes/SwiftFlutterFreshchatPlugin.swift:68:91: error: cannot convert value of type 'Any' to expected argument type 'String?'
                            Freshchat.sharedInstance().setUserPropertyforKey(kind, withValue: value)
                                                                                              ^~~~~
                                                                                                    as! String

**Comment by fayeed** [comment]
@MilenaSousa I don't have a mac so I really can't debug the code myself, and I am just making changes based on the errors that you are providing me with, anyway just made a few changes and updated the library to `1.1.7` you should check it. I am going to close this issue as the original purpose of this issue is completed If this doesn't work create a new issue. 
Hope this helps.
